
BEGIN;

DROP TABLE IF EXISTS "utilisateur",
"question",
"categorie",
"question_has_categorie";

-- -----------------------------------------------------
-- Table "app_user"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "utilisateur" (
  "id" serial PRIMARY KEY,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "prenom" text NULL,
  "nom" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "question"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "question" (
  "id" serial PRIMARY KEY,
  "titre" text NOT NULL,
  "description" text NULL,
  "lien_image" text NULL,
  "utilisateur_id" integer NOT NULL REFERENCES "utilisateur" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "categorie"
CREATE TABLE IF NOT EXISTS "categorie" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "question_has_categorie"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "question_has_categorie" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" integer NOT NULL REFERENCES "question"("id"),
  "categorie_id" integer NOT NULL REFERENCES "categorie" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  UNIQUE ("question_id", "categorie_id")
);

COMMIT;